baseURL = "/"
languageCode = "en-us"
theme = "kitchen"

[params]
enable_search = true  # set to true to show search bar

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[[menu.docs]]
identifier = "getting_started"
name = "Getting Started"
weight = 5

[[menu.docs]]
identifier = "drivers"
name = "Drivers"
weight = 10

[[menu.docs]]
identifier = "transports"
name = "Transports"
weight = 15

[[menu.docs]]
identifier = "provisioners"
name = "Provisioners"
weight = 20

[[menu.docs]]
identifier = "verifiers"
name = "Verifiers"
weight = 25

[[menu.docs]]
identifier = "reference"
name = "Reference"
weight = 50
